<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string></string>
	</array>
	<key>name</key>
	<string>CCSS</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#virtual</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>virtual</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.ccss</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.ccss</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Virtual element declaration.</string>
			<key>match</key>
			<string>(@(?:-gss-virtual|virtual))((?:\s"[^"]+")+)</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.ccss</string>
	<key>uuid</key>
	<string>cf93e33d-148f-40cc-ac4c-dc49dcd5f287</string>
</dict>
</plist>
