<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>gss</string>
	</array>
	<key>name</key>
	<string>GSS</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.css</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.ccss</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.vfl</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.vgl</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.gss</string>
	<key>uuid</key>
	<string>e100912f-23dc-45f3-91c5-93d2c898d6da</string>
</dict>
</plist>
